resources:
  containers:
  - container: nodejs_build_container
    image: nearform/docker_circleci:0.0.13

pool:
  vmImage: 'Ubuntu-16.04'

container: nodejs_build_container

steps:
- script: echo hello world

